name: mobile
description: "Mausam PersonalAI mobile app."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  geolocator: ^12.0.0
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_timezone: ^5.1.0
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
